#ifndef LNG_H
#define LNG_NUM 50
  #define LNG_H
extern wchar_t *lng[];

#define LNG_CREATE 9
#define LNG_WEEK 10
#define LNG_WORKDAYS 17
#define LNG_WEEKEND 18
#define LNG_ALLDAYS 19
#define LNG_REMINDS 20
#define REM_BEFORE 0
#define REM_AFTER 1
#define REM_BEFOREEND 2
#define REM_AFTEREND 3
#define REM_MINUTES 4
#define REMIND_TYPE 25
#define REMIND_DAYS 26
#define REMIND_DATE 27
#define REMIND_TTYPE 28
#define REMIND_TIME 29
#define REMIND_INTERVAL 30
#define OFF 31
#define ON 32
#define ON_WOUT_SOUND 33
#define TYPICAL 34
#define ANY_KEY 35
#define AUTO 36
#define ALLOW_ALL 37
#define FROM_LIST 38
#define NO 39
#define CHOOSE_PROF 40
#define MENU 41
#define CLONE 50
#define CLONE_HELP 51
#define INDICATION 52
#define COLORLEDS 53
#define ORANGELEDS 54
#define REDLEDS 55
#define VIBRA 56
#define SOUND 57
#define SECONDS 58
#define INTERVAL 59
#define MAXCOUNT 60
#define STANDART 61
#define CHOOSE 62
#define VOLUME 63
#define DAYS 64
#define ACTIONS 65
#define MUSICFILE 66
#define CURSTATUS 67
#define NOTSETTED 68
#define LNG_DATE 69
#define LNG_TIME 70
#define LNG_SAVE 71
#define LNG_ONCARD 72
#define LNG_ONPHONE 73
#endif
