#ifndef _LNG_H
#define _LNG_H

#define psz_savestate	"Save last panels state"
#define psz_backexit	"Back in root - Exit"
#define psz_sconchk		"Move cursor down on check"
#define psz_loopnav		"Enable loop navigation"

#define psz_scspeed		"Text scroll speed"
#define psz_scwait		"Text scroll wait"
#define psz_useboldf	"Use bold font"

#define psz_loadicons	"Load mcfileico.cfg"
#define psz_loadkeys	"Load mckeys.cfg"
#define psz_loadmui		"Load default.mclg"
#define psz_loadcs		"Load default.mccs"
#define psz_configpath	"mcconfig.cfg path"

#define psz_showhiddrv	"Show hidden drives"
#define psz_showmmc		"Show MMC"
#define psz_showhidden	"Show hidden files"
#define psz_showsystem	"Show system files"

#define psz_confirmexit	"On exit"
#define psz_confirmdel	"On delete"
#define psz_confirmdelr	"On delete readonly"
#define psz_confirmcopy	"On copy"
#define psz_confirmmove	"On move"
#define psz_confirmrepl	"On replace"

#define psz_autoexit_after			"AutoExit after (min)"
#define psz_autoexit_on_background	"AutoExit on background"

#define psz_zip_enable		"Enable zip support"
#define psz_zip_detect_by	"Detect zip by"

#define psz_7z_enable		"Enable 7z support"
#define psz_7z_detect_by	"Detect 7z by"

#define psz_temppath		"Path for temp files"
#define psz_cleartemp		"Delete temp files on exit"

#define psz_about		"mc v"version" \n(c) 2007 weclnt, greengo7\nThanks for efficient advices: Aru55, 1nvisible, captain_SISka"

#define psz_no			"No"
#define psz_yes			"Yes"

#define psz_content		"Content"
#define psz_extension	"Extension"

#define psz_drv_0		"Data"
#define psz_drv_1		"Cache"
#define psz_drv_2		"Config"
#define psz_drv_4		"MMC"

#define psz_mcvol		"MC"
#define psz_zipvol		"ZIP"

#define psz_errfile		"?"

#define psz_sm_common	"Common"
#define psz_sm_confirms	"Confirmations"
#define psz_sm_configs	"Configs"
#define psz_sm_disks	"Disks and files"
#define psz_sm_gui		"GUI"
#define psz_sm_autoexit	"AutoExit"
#define psz_sm_zip		"Zip"
#define psz_sm_7z		"7z"
#define psz_sm_archive	"Archives"

#define sz_no			L"Нет"
#define sz_yes			L"Да"

#define sz_byte			L"б"
#define sz_kbyte		L"Кб"
#define sz_mbyte		L"Мб"

#define sz_reconfig		L"Конфигу-\nрация обновлена!"
#define sz_lng			L"Язык"
#define sz_lngname		L"Русский"

#define sz_dirmking		L"Создание папок"
#define sz_copying		L"Копирование"
#define sz_moveing		L"Перемещение"
#define sz_deling		L"Удаление"

#define sz_mcmenu		L"Меню MC"
#define sz_select		L"Выбор"
#define sz_back			L"Назад"

#define sz_open			L"Открыть"
#define sz_file_m		L"Файл..."
#define sz_chk				L"Выделить"
#define sz_chkall			L"Выделить все"
#define sz_invchk			L"Инвертировать"
#define sz_unchall			L"Сбросить все"
#define sz_oper_m		L"Операции..."
#define sz_past				L"Вставить"
#define sz_cancel			L"Отменить"
#define sz_copy				L"Копировать"
#define sz_move				L"Переместить"
#define sz_del				L"Удалить"
#define sz_rename			L"Переименовать"
#define sz_newdir			L"Новая папка"
#define sz_newfile			L"Новый файл"
#define sz_prop			L"Свойства"
#define sz_view_m		L"Вид..."
#define sz_sort_m			L"Сортировка..."
#define sz_sortn				L"По имени"
#define sz_sorte				L"По типу"
#define sz_sorts				L"По размеру"
#define sz_sortd				L"По дате"
#define sz_sortr				L"Обратная"
#define sz_filter			L"Фильтр"
#define sz_refresh			L"Обновить"
#define sz_misc_m		L"Разное..."
#define sz_bm_m				L"Закладки..."
#define sz_add					L"Добавить"
#define sz_bml					L"Список"
#define sz_drvinf			L"Диски"
#define sz_settings			L"Настройки"
#define sz_about_m			L"Об эльфе..."
#define sz_exit			L"Выход"

#define sz_sendfile             L"Передать через BT"

#define sz_bm			L"Закладка"

#define sz_name			L"Имя"
#define sz_fullname		L"Полное имя"
#define sz_size			L"Размер"
#define sz_global		L"Общий"
#define sz_folders		L"Папок"
#define sz_files		L"Файлов"
#define sz_date			L"Дата создания"
#define sz_attr			L"Атрибуты"
#define sz_readonly		L"Только чтение"
#define sz_hidden		L"Скрытый"
#define sz_system		L"Системный"
#define sz_arh			L"Архивный"
#define sz_subdirs		L"Обрабатывать подкаталоги"
#define sz_ncsize		L"Несжатый"
#define sz_csize		L"Сжатый"
#define sz_cglobal		L"Общий сжатый"

#define sz_pmt_del		L"Удалить?"
#define sz_pmt_rodel	L"Файл %s только для чтения.\nУдалить?"
#define sz_pmt_copy		L"Копировать?"
#define sz_pmt_move		L"Переме-\nстить?"
#define sz_pmt_stop		L"Прервать?"
#define sz_pmt_cancel	L"Очистить буфер?"
#define sz_pmt_exists	L"Файл существует. Заменить?"
#define sz_pmt_exit		L"Выйти из MC?"
#define sz_pmt_impcs	L"Применить цветовую схему?"
#define sz_pmt_implg	L"Применить язык?"

#define sz_err_attrset		L"Не удалось задать атрибуты!"
#define sz_err_makedir		L"Не удалось создать папку!"
#define sz_err_rename		L"Не удалось переиме-\nновать!"
#define sz_err_delete		L"Не удалось удалить!"
#define sz_err_badname_t	L"Неверное имя: %ls"
#define sz_err_baddrv_t		L"Неверный диск! %t"
#define sz_err_resnok		L"Выполнено с ошибками!"
#define sz_err_nofiles		L"Нет файлов!"
#define sz_err_badname		L"Неверное имя!"
#define sz_err_badkey		L"Ошибка конфигурации кнопок!"
#define sz_err_badformat	L"Неверный формат или файл поврежден!"
#define sz_err_nomemory		L"Не хватает памяти!"
#define sz_err_makefile		L"Не удалось создать новый файл!"
#define sz_err_ziperr		L"Ошибка Zip: %d в %t!"

#define sz_msg_zreading			L"Чтение архива"
#define sz_msg_showhid_files	L"Показывать скрытые файлы"
#define sz_msg_showsys_files	L"Показывать системные файлы"
#define sz_msg_showhidsys_files	L"Показывать скрытые и системные файлы"
#define sz_msg_showhid_drv		L"Показывать скрытые диски"

#endif
