#define LANGUAGE "Русский"
#define TRANSLATED_BY L""

//Управление
#define LG_GFGSETCTRL         "Настройки управления"
#define LG_GFGCTRLMODE          "Режим управления"
#define LG_GFGMENUONLY            "Только меню"
#define LG_GFGSETBUTTONSONLY      "Только кнопки"
#define LG_GFGMENUKEY           "Кнопка меню"
#define LG_GFGSETBUTTONS        "Кнопки"
#define LG_GFGSHOWKEY             "Кнопка паказать/спрятать"
#define LG_GFGCELLIDNAMEKEY       "Кнопка CellID/Имя"
#define LG_GFGAUTOLOCATIONKEY     "Кнопка автодобавления места"
#define LG_GFGIGNOREKEYLOCK     "Игнорировать блок. клавиш"

//Основное
#define LG_GFGSETMAIN         "Основные настройки"
#define LG_CFGNOTHING             "ничего"
#define LG_CFGNAMEONLY            "имя только"
#define LG_CFGIMAGEONLY           "картинку только"
#define LG_CFGNAMEIMAGE           "имя и картинку"
#define LG_GFGCELLIDMODE        "Режим CellID"
#define LG_GFGHEX                 "шестнадцатиричный"
#define LG_GFGDEC                 "десятичный"
#define LG_GFGLOCATION          "Расположение"
#define LG_GFGFIRSTOPERATORLINE   "Первая строка оператора"
#define LG_GFGSECONDOPERATORLINE  "Вторая строка оператора"
#define LG_GFGTHIRDOPERATORLINE   "Третья строка оператора"
#define LG_GFGNOTESBOX            "Заметки"
#define LG_GFGDATE                "Дата"
#define LG_GFGBIGCLOCK            "Большие часы"
#define LG_GFGCLOCK               "Часы"
#define LG_GFGBOTTOMLEFT          "Слева внизу"
#define LG_GFGABOVEBOTTOMLEFT     "На одну строку выше слева внизу"
#define LG_GFGCUSTOM              "Свое расположение"
#define LG_GFGCUSTOMLOCATION    "Свое расположение"
#define LG_GFGFONT                "Шрифт"
#define LG_GFGCOLOR               "Цвет текста"
#define LG_GFGBORDER              "Цвет обводки"
#define LG_GFGALIGN               "Выравнивание"
#define LG_GFGLEFT                  "Слева"
#define LG_GFGRIGHT                 "Справа"
#define LG_GFGCENTER                "По центру"
#define LG_GFGHIGHLIGHT           "Обводка"
#define LG_GFGPOSITION            "XY координаты"
#define LG_GFGVIBRATEONCHANGE   "Вибрация при изменении LAC:CID"
#define LG_GFGNEVERVIBRATE        "Отключено"
#define LG_GFGVIBRATE3X70         "3x 70 мсек"
#define LG_GFGVIBRATE1X250        "1x 250 мсек"
#define LG_GFGVIBRATE1X500        "1x 500 мсек"
#define LG_GFGNEWACTIONTIMEOUT  "Задержка действия (мин)"
#define LG_GFGAUTOLOCATION      "Иконка автодобавления места"
#define LG_GFGSHOW                 "Показывать"
#define LG_GFGFILE                 "Файл картинки"
#define LG_GFGIMGAGES           "Картинки"
#define LG_GFGPOSITIONSIZE        "Размер & координаты"
#define LG_GFGPATHIMG             "Папка с картинками"
#define LG_GFGLOCATIONFILE      "Файл базы данных"
//Действия
#define LG_GFGSETACTIONS      "Настройки действий"
#define LG_CFGDEFAULTPROFILE    "Профиль по умолчанию"
#define LG_GFGNONE                "Отключено"
#define LG_GFGNORMAL              "Обычный"
#define LG_GFGMEETING             "Совещание"
#define LG_GFGINCAR               "В автомобиле"
#define LG_GFGOUTDOORS            "На улице"
#define LG_GFGHANDSFREE           "Аудиоустр."
#define LG_GFGHOME                "Дома"
#define LG_GFGOFFICE              "На работе"
#define LG_CFGMANUALPROFILES    "Профиль вкл. вручную"
#define LG_CFGMANUALPROFILE       "Профиль"
#define LG_CFGPLACES            "Места"
#define LG_CFGPLACE               "Место"
#define LG_CFGPLACEENABLE           "Включено"
#define LG_CFGPLACENAME             "Имя"
#define LG_CFGPROFILE               "Профиль"
#define LG_CFGVIBRATE               "Вибрация"
#define LG_CFGSOUND                 "Звуковой файл"
#define LG_CFGENABLESOUND             "Включено"
#define LG_CFGFILE                    "Файл"
#define LG_GFGPATHSOUND         "Папка со звуками"
//Логинг
#define LG_GFGSETLOG          "Настройки логов"
#define LG_GFGLOGMODE           "Режим"
#define LG_GFGNEVERLOG            "Отключено"
#define LG_GFGEVERYCHANGELOG      "Каждое изменение"
#define LG_GFGNAMECHANGELOG       "Только изменение имени"
#define LG_GFGKNOWNLOG            "Только известные места"
#define LG_GFGUNKNOWNLOG          "Только неизвестные места"
#define LG_GFGDATEFORMAT        "Формат даты"
#define LG_GFGLOGEXT            "Расширение файла лога"
#define LG_GFGTXT                 ".txt"
#define LG_GFGINI                 ".ini"
#define LG_GFGPATHLOGS          "Папка для логов"
//Другое
#define LG_GFGSETOTHER        "Другие настройки"
#define LG_GFGREFRESH           "Интревал обновления (мсек)"
#define LG_GFGSTANDBAYONLY      "Только в режиме ожидания"
#define LG_GFGSETINGDFS         "Сохранять профиль в GDFS"
#define LG_GFGSILENT            "Звуки в режиме без звука"
#define LG_GFGSETENCODING       "Настойки кодировки"
#define LG_GFGENCODETYPE          "Тип кодировки"
#define LG_GFGENCODEFILE            "Файл кодировки"
#define LG_GFGENCODEMAP             "Китайская кодовая стр."
#define LG_GFGPATHENCODE          "Файл кодировки"
#define LG_GFGCODEMAPADDR         "Адрес китайской кодовой стр."
#define LG_GFGPATHBCFGEDIT      "BcfgEdit.elf"

//Меню
#define LG_SHOW                    L"Показать название"
#define LG_HIDE                    L"Спрятать название"
#define LG_CELLID                  L"Показать CellID"
#define LG_NAME                    L"Показать Имя"
#define LG_AUTOLOCATION_ON         L"Вкл. автодобавление места"
#define LG_AUTOLOCATION_OFF        L"Выкл. автодобавление места"
#define LG_SETTINGS                L"Настройки"
#define LG_ABOUT                   L"Oб эльфе"

//Сообщения
#define LG_GFGBCFGEDITNOTFOUND     L"BcfgEdit.elf не найден!"
#define LG_GFGINCORRECTCODEMAPADDR L"Неправильный адрес кодовой страницы!"
#define LG_GFGENCODEFILENOTFOUND   L"Файл кодировки не найден!"
#define LG_ALREADY_STARTED         L"Уже запущен!"
#define LG_DBLOADERROR             L"Не могу загрузить базу данных!"
#define LG_AUTOLOCATIONOFF         L"Автодобавление места выключено!"
#define LG_CURRENTLOCATION         L"Текущее место:"
#define LG_AUTOLOCATIONIMG         L"Иконка вкл. автодобавления места не найдена!"
#define LG_UPDSETTING              L"Настройки MiniGPS применены!"
