#ifdef ENG

#define lng_lvlVerticalView "Vertical view"
#define lng_lvlHorizontalView "Horizontal view"
#define lng_chkStandartWindow "Standart window"
#define lng_lvlTitle "Title"
#define lng_lvlAlbum "Album"
#define lng_lvlArtist "Artist"
#define lng_lvlYear "Year"
#define lng_lvlGenre "Genre"
#define lng_lvlBitrate "Bitrate"
#define lng_lvlFrequency "Frequency"
#define lng_lvlChannels "Channels"
#define lng_lvlCover "Cover"
#define lng_lvlProgressBar "Progressbar"
#define lng_lvlPlayStopIcon "Play/Stop icon"
#define lng_lvlTitleIcon "Title icon"
#define lng_lvlAlbumIcon "Album icon"
#define lng_lvlArtistIcon "Artist icon"
#define lng_lvlEqualizerIcon "Equalizer preset icon"
#define lng_lvlTrackNumber "Track num"
#define lng_lvlTracksCount "Tracks' count"
#define lng_lvlCurrentTime "Current time"
#define lng_lvlTimeLeft "Time left"
#define lng_lvlFullTime "Full time"

#define lng_itmShow "Show"
#define lng_itmFont "Font"
#define lng_itmPosition "Position"
#define lng_itmPositionAndSize "Position and size"
#define lng_itmColor "Color"
#define lng_itmSecondColor "Second color"
#define lng_itmCentering "Centering"
#define lng_itmHighlightColor "Highlight color"
#define lng_itmMask "Text mask"
#define lng_itmVbrMask "VBR text"
#define lng_chkHighlight "Use highlight"
#define lng_chkUsePauseIcon "Use pause icon"
#define lng_chkLeft "Left"
#define lng_chkRight "Right"
#define lng_chkCenter "Center"
#define lng_keyRotation "Rotation key"
#define lng_chkAccelerometer "Use accelerometer"
#define lng_chkAlbumPng "Use album/cover.png"
#define lng_chkImagePriority "Image priority"
#define lng_chkFirstInternal "First internal, then external"
#define lng_chkOnlyExternal "Only external"
#define lng_chkOnlyInternal "Only internal"
#define lng_chkUseVbr "Use VBR"
#define lng_standartBitrateMask L"%d kb/s"
#define lng_standartFrequencyMask L"%d Hz"
#define lng_lvlLeftIcon "Left arrow"
#define lng_lvlRightIcon "Right arrow"
#define lng_lvlCenterIcon "Play/Stop"
#define lng_lvlUpIcon "Up arrow"
#define lng_lvlDownIcon "Down arrow"
#define lng_lvlNavigation "Navigation block"

#define lng_lvlShuffleMode "Shuffle mode"
#define lng_lvlRepeatMode "Repeat mode"
#define lng_lvlStereoWidening "Stereo widening"
#define lng_lvlIcons "Icons"
#define lng_lvlBackground "Background"


#define lng_chkUnicalSkinData "Use skin bcfg"
#define lng_chkSkinAndCommonData "Skin and common data"
#define lng_chkOnlyCommonData "Only common data"
#define lng_lvlRestrictions "Restrictions"
#define lng_chkRestriction_Cover "No cover->No album name"

#define lng_lvlVolumeBar "VolumeBar"
#define lng_itmCurVolume "Color of current volume"
#define lng_itmLeftVolume "Background color"

#define lng_chkAccelOn "On"
#define lng_chkAccelRotate "Turn off after pressing key"
#define lng_chkAccelOff "Off"
#define lng_chkPhone "Phone"
#define lng_chkNotSelected "Autodetect"

#define lng_chkHideSoftkeys "Hide softkeys"
#define lng_chkNo "Don't hide"
#define lng_chkInHorizontalMode "In horizontal mode"
#define lng_chkInVerticalMode "In vertical mode"
#define lng_chkEverywhere "Everywhere" 

#define lng_chkInitOrientation "Default orientation"
#define lng_chkVertical "Vertical"
#define lng_chkHorizontal "Horizontal"

#define lng_chkHighlightType "Highlight type"
#define lng_chkDefault "Typical"
#define lng_chkDefault2 "Typical, variant 2"
#define lng_chkShadow "Shadow"

#define lng_msgSkinNotLoaded L"Skin isn't loaded yet. Please, start player first"
#define lng_msgSkinsInstalled L"New skins installed"
#define lng_msgSkinsFound L"New skins found. Please, start player to install them"
#define lng_msgW580detected L"W580/W850 detected. Saved."
#define lng_msgW610detected L"W610/W660/W880 detected. Saved."
#define lng_msgNotSupported L"Your phone is not Walkman 2.0. Sorry, walkman 1.4 isn't supported. Use PlayerMod ;-)"
#define lng_txtAlreadyRunned L"WalkmanDisplay is already runned"
#define lng_txtMissedConsts L"Missed constants: \n"
#endif
