
#ifdef RUS
#define lng_lvlVerticalView "Вертикальное положение"
#define lng_lvlHorizontalView "Горизонтальное положение"
#define lng_chkStandartWindow "Стандартная прорисовка"
#define lng_lvlTitle "Название"
#define lng_lvlAlbum "Альбом"
#define lng_lvlArtist "Исполнитель"
#define lng_lvlYear "Год"
#define lng_lvlGenre "Жанр"
#define lng_lvlBitrate "Битрейт"
#define lng_lvlFrequency "Частота дискретизации"
#define lng_lvlChannels "Каналы"
#define lng_lvlCover "Обложка"
#define lng_lvlProgressBar "Прогрессбар"
#define lng_lvlPlayStopIcon "Проигр./стоп"
#define lng_lvlTitleIcon "Название"
#define lng_lvlAlbumIcon "Альбом"
#define lng_lvlArtistIcon "Исполнитель"
#define lng_lvlEqualizerIcon "Эквалайзер"
#define lng_lvlTrackNumber "Номер трека"
#define lng_lvlTracksCount "Кол-во треков"
#define lng_lvlCurrentTime "Текущее время"
#define lng_lvlTimeLeft "Оставшееся время"
#define lng_lvlFullTime "Полное время"

#define lng_itmShow "Показывать"
#define lng_itmFont "Шрифт"
#define lng_itmPosition "Позиция"
#define lng_itmPositionAndSize "Позиция и размер"
#define lng_itmColor "Цвет"
#define lng_itmSecondColor "Цвет обводки"
#define lng_itmCentering "Центрирование"
#define lng_itmHighlightColor "Цвет обводки"
#define lng_itmMask "Маска текста"
#define lng_itmVbrMask "Текст VBR"
#define lng_chkHighlight "Обводка"
#define lng_chkUsePauseIcon "Исп. иконку 'Пауза'"
#define lng_chkLeft "По левому краю"
#define lng_chkRight "По правому краю"
#define lng_chkCenter "По центру"
#define lng_keyRotation "Кнопка переключения вида"
#define lng_chkAccelerometer "Исп. акселерометр"
#define lng_chkAlbumPng "Исп. album/cover.png"
#define lng_chkImagePriority "Приоритет изображ."
#define lng_chkFirstInternal "Сначала внутр., потом внешнее"
#define lng_chkOnlyExternal "Только внешнее"
#define lng_chkOnlyInternal "Только внутр."
#define lng_chkUseVbr "Исп. VBR"
#define lng_standartBitrateMask L"%d кб/с"
#define lng_standartFrequencyMask L"%d Гц"
#define lng_lvlLeftIcon "Пред. трек"
#define lng_lvlRightIcon "След. трек"
#define lng_lvlCenterIcon "Проигр./Стоп"
#define lng_lvlUpIcon "Вверх"
#define lng_lvlDownIcon "Вниз"
#define lng_lvlNavigation "Навигац. блок"
#define lng_lvlShuffleMode "Случайный порядок"
#define lng_lvlRepeatMode "Повтор"
#define lng_lvlStereoWidening "Расширенное стерео"
#define lng_chkUnicalSkinData "Исп. bcfg из стиля плеера"
#define lng_chkSkinAndCommonData "Общий+стиль плеера"
#define lng_chkOnlyCommonData "Только общий стиль"
#define lng_lvlIcons "Иконки"
#define lng_lvlBackground "Фон"
#define lng_lvlRestrictions "Ограничения"
#define lng_chkRestriction_Cover "Нет обложки->Нет назв. альбома"

#define lng_lvlVolumeBar "Индикатор громкости"
#define lng_itmCurVolume "Цвет текущей громкости"
#define lng_itmLeftVolume "Цвет фона"

#define lng_chkAccelOn "Вкл."
#define lng_chkAccelRotate "Откл. после наж. кнопки"
#define lng_chkAccelOff "Откл."


#define lng_chkPhone "Телефон"
#define lng_chkNotSelected "Автоматически"

#define lng_chkHideSoftkeys "Скрывать софт-кнопки"
#define lng_chkNo "Не скрывать"
#define lng_chkInHorizontalMode "В горизонтальном режиме"
#define lng_chkInVerticalMode "В вертикальном режиме"
#define lng_chkEverywhere "Везде" 
#define lng_chkInitOrientation "Нач. ориентация экрана"
#define lng_chkVertical "Вертикальная"
#define lng_chkHorizontal "Горизонтальная"

#define lng_chkHighlightType "Тип обводки"
#define lng_chkDefault "Обычная"
#define lng_chkDefault2 "Обычная, вариант 2"
#define lng_chkShadow "Тень"

#define lng_msgSkinNotLoaded L"Оформление ещё не загружено. Пожалуйста, запустите сначала плеер"
#define lng_msgSkinsInstalled L"Стили оформления плеера установлены"
#define lng_msgSkinsFound L"Обнаружены новые стили оформления плеера. Пожалуйста, запустите плеер для их установки"
#define lng_msgW580detected L"W580/W850 обнаружен. Сохранено."
#define lng_msgW610detected L"W610/W660/W880 обнаружен. Сохранено."
#define lng_msgNotSupported L"У вашего телефона плеер не Walkman 2.0. Извините, но Walkman 1.4 не поддерживается. Используйте PlayerMod ;-)"
#define lng_msgMigrated L"Конфигурационный файл обновлён"
#define lng_txtAlreadyRunned L"WalkmanDisplay уже запущен"
#define lng_txtMissedConsts L"Отсутствующие константы: \n"
#endif
