/*
* Information for translators!
*
* This is the English language file, to translate it, just edit the lines,
* translate strings between '"' marks. In some places there is an L like L"...",
* don't care about it, don't change it. Add your name to TRANSLATED_BY and
* set LANGUAGE to yours.
*
* Then give it to us somehow, so that we can make the version with your
* language, post at the topics where we posted the elf
* (http://mobilefree.ru/newbb_plus/viewtopic.php?topic_id= )
*
* Regards,
*    copini, zoyd, Ploik, mousex, Joker XT, Stonos and BigHercules
*/

#define LANGUAGE "Chinese"
#define TRANSLATED_BY L""

//Control
#define LG_GFGSETCTRL         "Control settings"
#define LG_GFGCTRLMODE          "Control mode"
#define LG_GFGMENUONLY            "Menu only"
#define LG_GFGSETBUTTONSONLY      "Buttons only"
#define LG_GFGMENUKEY           "Menu Key"
#define LG_GFGSETBUTTONS        "Buttons"
#define LG_GFGSHOWKEY             "Show Key"
#define LG_GFGCELLIDNAMEKEY       "CellID/Name Key"
#define LG_GFGAUTOLOCATIONKEY     "Auto location key"
#define LG_GFGIGNOREKEYLOCK     "Ignore Keylock"

//Main
#define LG_GFGSETMAIN         "Main settings"
#define LG_CFGNOTHING             "nothing"
#define LG_CFGNAMEONLY            "name only"
#define LG_CFGIMAGEONLY           "image only"
#define LG_CFGNAMEIMAGE           "name & image"
#define LG_GFGCELLIDMODE        "CellID Mode"
#define LG_GFGHEX                 "hex"
#define LG_GFGDEC                 "decimal"
#define LG_GFGLOCATION          "Location"
#define LG_GFGFIRSTOPERATORLINE   "First Operator Line"
#define LG_GFGSECONDOPERATORLINE  "Second Operator Line"
#define LG_GFGTHIRDOPERATORLINE   "Third Operator Line"
#define LG_GFGNOTESBOX            "Notesbox"
#define LG_GFGDATE                "Date"
#define LG_GFGBIGCLOCK            "Big Clock"
#define LG_GFGCLOCK               "Clock"
#define LG_GFGBOTTOMLEFT          "Bottom left"
#define LG_GFGABOVEBOTTOMLEFT     "One line above bottom left"
#define LG_GFGCUSTOM              "Custom Location"
#define LG_GFGCUSTOMLOCATION    "Custom Location"
#define LG_GFGFONT                "Font"
#define LG_GFGCOLOR               "Color"
#define LG_GFGBORDER              "Border"
#define LG_GFGALIGN               "Alignment"
#define LG_GFGLEFT                  "left"
#define LG_GFGRIGHT                 "right"
#define LG_GFGCENTER                "center"
#define LG_GFGHIGHLIGHT           "Highlight"
#define LG_GFGPOSITION            "XY Position"
#define LG_GFGVIBRATEONCHANGE   "Vibration when LAC:CID changes"
#define LG_GFGNEVERVIBRATE        "Disabled"
#define LG_GFGVIBRATE3X70         "3x 70 msec"
#define LG_GFGVIBRATE1X250        "1x 250 msec"
#define LG_GFGVIBRATE1X500        "1x 500 msec"
#define LG_GFGNEWACTIONTIMEOUT  "New Action Timeout (min)"
#define LG_GFGAUTOLOCATION      "Auto location Icon"
#define LG_GFGSHOW                 "Show"
#define LG_GFGFILE                 "File"
#define LG_GFGIMGAGES           "Images"
#define LG_GFGPOSITIONSIZE        "Size & Position"
#define LG_GFGPATHIMG             "Images Folder"
#define LG_GFGLOCATIONFILE      "Database file"
//Actions
#define LG_GFGSETACTIONS      "Action settings"
#define LG_CFGDEFAULTPROFILE    "Default profile"
#define LG_GFGNONE                "Disabled"
#define LG_GFGNORMAL              "Normal"
#define LG_GFGMEETING             "Meeting"
#define LG_GFGINCAR               "In car"
#define LG_GFGOUTDOORS            "Outdoors"
#define LG_GFGHANDSFREE           "Handsfree"
#define LG_GFGHOME                "Home"
#define LG_GFGOFFICE              "Office"
#define LG_CFGMANUALPROFILES    "Manual profiles"
#define LG_CFGMANUALPROFILE       "Profile"
#define LG_CFGPLACES            "Places"
#define LG_CFGPLACE               "Place"
#define LG_CFGPLACEENABLE           "Enable"
#define LG_CFGPLACENAME             "Name"
#define LG_CFGPROFILE               "Profile"
#define LG_CFGVIBRATE               "Vibrate"
#define LG_CFGSOUND                 "Sound"
#define LG_CFGENABLESOUND             "Enable"
#define LG_CFGFILE                    "File"
#define LG_GFGPATHSOUND         "Sound Folder"
//Logging
#define LG_GFGSETLOG          "Log settings"
#define LG_GFGLOGMODE           "Log Mode"
#define LG_GFGNEVERLOG            "Disabled"
#define LG_GFGEVERYCHANGELOG      "Every change"
#define LG_GFGNAMECHANGELOG       "Only Namechanges"
#define LG_GFGKNOWNLOG            "Only known places"
#define LG_GFGUNKNOWNLOG          "Only unknown places"
#define LG_GFGDATEFORMAT        "Dateformat"
#define LG_GFGLOGEXT            "Log Extension"
#define LG_GFGTXT                 ".txt"
#define LG_GFGINI                 ".ini"
#define LG_GFGPATHLOGS          "Log Folder"
//Other
#define LG_GFGSETOTHER        "Other settings"
#define LG_GFGREFRESH           "Refresh interval (msec)"
#define LG_GFGSTANDBAYONLY      "In standby only"
#define LG_GFGSETINGDFS         "Store a profile in GDFS"
#define LG_GFGSILENT            "Sound on silent mode"
#define LG_GFGSETENCODING       "Encoding settings"
#define LG_GFGENCODETYPE          "Encoding type"
#define LG_GFGENCODEFILE            "Encoding file"
#define LG_GFGENCODEMAP             "Chinese code map"
#define LG_GFGPATHENCODE          "Language Encoding file"
#define LG_GFGCODEMAPADDR         "Chinese code map address"
#define LG_GFGPATHBCFGEDIT      "BcfgEdit.elf"

//Menu
#define LG_SHOW                    L"Show location"
#define LG_HIDE                    L"Hide location"
#define LG_CELLID                  L"Show CellID"
#define LG_NAME                    L"Show Name"
#define LG_AUTOLOCATION_ON         L"Turn on autolocation"
#define LG_AUTOLOCATION_OFF        L"Turn off autolocation"
#define LG_SETTINGS                L"Settings"
#define LG_ABOUT                   L"About"

//Messages
#define LG_GFGBCFGEDITNOTFOUND     L"BcfgEdit.elf not found!"
#define LG_GFGINCORRECTCODEMAPADDR L"Incorrect code map address!"
#define LG_GFGENCODEFILENOTFOUND   L"Encoding file not found!"
#define LG_ALREADY_STARTED         L"Already started!"
#define LG_DBLOADERROR             L"Can't load the database file!"
#define LG_AUTOLOCATIONOFF         L"Auto location disabled."
#define LG_CURRENTLOCATION         L"Current location:"
#define LG_AUTOLOCATIONIMG         L"Auto location icon not found!"
#define LG_UPDSETTING              L"MiniGPS's settings updated!"

