#ifndef SKIN_DATA_H
#define SKIN_DATA_H
extern const int standartwnd;
extern const int title_show;
extern const int title_font;
extern const RECT title_rc;
/*
extern const int title_x;
extern const int title_y;
*/
extern const unsigned int title_color;
extern const unsigned int title_scolor;
extern const int title_ct;
extern const int album_show;
extern const int album_font;
extern const RECT album_rc;
extern const unsigned int album_color;
extern const unsigned int album_scolor;
extern const int album_ct;
extern const int artist_show;
extern const int artist_font;
extern const RECT artist_rc;
extern const unsigned int artist_color;
extern const unsigned int artist_scolor;
extern const int artist_ct;
extern const int year_show;
extern const int year_font;
extern const RECT year_rc;
extern const unsigned int year_color;
extern const unsigned int year_scolor;
extern const int year_ct;
extern const int genre_show;
extern const int genre_font;
extern const RECT genre_rc;
extern const unsigned int genre_color;
extern const unsigned int genre_scolor;
extern const int genre_ct;
extern const int trackn_show;
extern const int trackn_font;
extern const RECT trackn_rc;
extern const unsigned int trackn_color;
extern const unsigned int trackn_scolor;
extern const int trackn_ct;
extern const wchar_t trackn_mask[49];
extern const int tracks_show;
extern const int tracks_font;
extern const RECT tracks_rc;
extern const unsigned int tracks_color;
extern const unsigned int tracks_scolor;
extern const int tracks_ct;
extern const wchar_t tracks_mask[49];
extern const int ctime_show;
extern const int ctime_font;
extern const RECT ctime_rc;
extern const unsigned int ctime_color;
extern const unsigned int ctime_scolor;
extern const int ctime_ct;
extern const wchar_t ctime_mask[49];
extern const int ftime_show;
extern const int ftime_font;
extern const RECT ftime_rc;
extern const unsigned int ftime_color;
extern const unsigned int ftime_scolor;
extern const int ftime_ct;
extern const wchar_t ftime_mask[49];
extern const int ltime_show;
extern const int ltime_font;
extern const RECT ltime_rc;
extern const unsigned int ltime_color;
extern const unsigned int ltime_scolor;
extern const int ltime_ct;
extern const wchar_t ltime_mask[49];
extern const int bitrate_show;
extern const int bitrate_font;
extern const RECT bitrate_rc;
extern const unsigned int bitrate_color;
extern const unsigned int bitrate_scolor;
extern const int bitrate_ct;
extern const wchar_t bitrate_mask[49];
extern const wchar_t bitrate_vbr[49];
extern const int freq_show;
extern const int freq_font;
extern const RECT freq_rc;
extern const unsigned int freq_color;
extern const unsigned int freq_scolor;
extern const int freq_ct;
extern const wchar_t freq_mask[49];
extern const int ch_show;
extern const int ch_font;
extern const RECT ch_rc;
extern const unsigned int ch_color;
extern const unsigned int ch_scolor;
extern const int ch_ct;
extern const int ProgressBar_Show;
extern const RECT pbrect;
extern const unsigned int ProgressBar_cColor;
extern const unsigned int ProgressBar_oColor;
extern const unsigned int ProgressBar_bColor;
extern const int ProgressBar_highlight;
extern const int cover_show;;
extern const RECT cover_rect;
extern const int ticn_show;
extern const RECT ticn_rect;
extern const int alicn_show;
extern const RECT alicn_rect;
extern const int aricn_show;
extern const RECT aricn_rect;
extern const int pls_show;
extern const RECT pls_rect;
extern const int eq_preset_show;
extern const RECT eq_preset_rect;

extern const int title_show_h;
extern const int title_font_h;
extern const RECT title_rc_h;
extern const unsigned int title_color_h;
extern const unsigned int title_scolor_h;
extern const int title_ct_h;
extern const int album_show_h;
extern const int album_font_h;
extern const RECT album_rc_h;
extern const unsigned int album_color_h;
extern const unsigned int album_scolor_h;
extern const int album_ct_h;
extern const int artist_show_h;
extern const int artist_font_h;
extern const RECT artist_rc_h;
extern const unsigned int artist_color_h;
extern const unsigned int artist_scolor_h;
extern const int artist_ct_h;
extern const int year_show_h;
extern const int year_font_h;
extern const RECT year_rc_h;
extern const unsigned int year_color_h;
extern const unsigned int year_scolor_h;
extern const int year_ct_h;
extern const int genre_show_h;
extern const int genre_font_h;
extern const RECT genre_rc_h;
extern const unsigned int genre_color_h;
extern const unsigned int genre_scolor_h;
extern const int genre_ct_h;
extern const int trackn_show_h;
extern const int trackn_font_h;
extern const RECT trackn_rc_h;
extern const unsigned int trackn_color_h;
extern const unsigned int trackn_scolor_h;
extern const int trackn_ct_h;
extern const wchar_t trackn_mask_h[49];
extern const int tracks_show_h;
extern const int tracks_font_h;
extern const RECT tracks_rc_h;
extern const unsigned int tracks_color_h;
extern const unsigned int tracks_scolor_h;
extern const int tracks_ct_h;
extern const wchar_t tracks_mask_h[49];
extern const int ctime_show_h;
extern const int ctime_font_h;
extern const RECT ctime_rc_h;
extern const unsigned int ctime_color_h;
extern const unsigned int ctime_scolor_h;
extern const int ctime_ct_h;
extern const wchar_t ctime_mask_h[49];
extern const int ftime_show_h;
extern const int ftime_font_h;
extern const RECT ftime_rc_h;
extern const unsigned int ftime_color_h;
extern const unsigned int ftime_scolor_h;
extern const int ftime_ct_h;
extern const wchar_t ftime_mask_h[49];
extern const int ltime_show_h;
extern const int ltime_font_h;
extern const RECT ltime_rc_h;
extern const unsigned int ltime_color_h;
extern const unsigned int ltime_scolor_h;
extern const int ltime_ct_h;
extern const wchar_t ltime_mask_h[49];
extern const int bitrate_show_h;
extern const int bitrate_font_h;
extern const RECT bitrate_rc_h;
extern const unsigned int bitrate_color_h;
extern const unsigned int bitrate_scolor_h;
extern const int bitrate_ct_h;
extern const wchar_t bitrate_mask_h[49];
extern const wchar_t bitrate_vbr_h[49];
extern const int freq_show_h;
extern const int freq_font_h;
extern const RECT freq_rc_h;
extern const unsigned int freq_color_h;
extern const unsigned int freq_scolor_h;
extern const int freq_ct_h;
extern const wchar_t freq_mask_h[49];
extern const int ch_show_h;
extern const int ch_font_h;
extern const RECT ch_rc_h;
extern const unsigned int ch_color_h;
extern const unsigned int ch_scolor_h;
extern const int ch_ct_h;
extern const int ProgressBar_Show_h;
extern const RECT pbrect_h;
extern const unsigned int ProgressBar_cColor_h;
extern const unsigned int ProgressBar_oColor_h;
extern const unsigned int ProgressBar_bColor_h;
extern const int ProgressBar_highlight_h;
extern const int cover_show_h;
extern const RECT cover_rect_h;
extern const int ticn_show_h;
extern const RECT ticn_rect_h;
extern const int alicn_show_h;
extern const RECT alicn_rect_h;
extern const int aricn_show_h;
extern const RECT aricn_rect_h;
extern const int pls_show_h;
extern const RECT pls_rect_h;

extern const int eq_preset_show_h;
extern const RECT eq_preset_rect_h;

extern const int upimg_show;
extern const int upimg_show_h;
extern const RECT upimg_rect;
extern const RECT upimg_rect_h;
extern const int downimg_show;
extern const int downimg_show_h;
extern const RECT downimg_rect;
extern const RECT downimg_rect_h;
extern const int leftimg_show;
extern const int leftimg_show_h;
extern const RECT leftimg_rect;
extern const RECT leftimg_rect_h;
extern const int rightimg_show;
extern const int rightimg_show_h;
extern const RECT rightimg_rect;
extern const RECT rightimg_rect_h;
extern const int centerimg_show;
extern const int centerimg_show_h;
extern const RECT centerimg_rect;
extern const RECT centerimg_rect_h;
extern const int navigimg_show;
extern const int navigimg_show_h;
extern const RECT navigimg_rect;
extern const RECT navigimg_rect_h;
extern const int repeat_show;
extern const int repeat_show_h;
extern const RECT repeat_rect;
extern const RECT repeat_rect_h;
extern const int shuffle_show;
extern const int shuffle_show_h;
extern const RECT shuffle_rect;
extern const RECT shuffle_rect_h;

extern const int stereo_show;
extern const int stereo_show_h;
extern const RECT stereo_rect;
extern const RECT stereo_rect_h;

extern const int title_hl;
extern const int title_hl_h;
extern const int album_hl;
extern const int album_hl_h;
extern const int artist_hl;
extern const int artist_hl_h;
extern const int genre_hl;
extern const int genre_hl_h;
extern const int year_hl;
extern const int year_hl_h;
extern const int bitrate_hl;
extern const int bitrate_hl_h;
extern const int trackn_hl;
extern const int trackn_hl_h;
extern const int tracks_hl;
extern const int tracks_hl_h;
extern const int ch_hl;
extern const int ch_hl_h;
extern const int freq_hl;
extern const int freq_hl_h;
extern const int ctime_hl;
extern const int ctime_hl_h;
extern const int ltime_hl;
extern const int ltime_hl_h;
extern const int ftime_hl;
extern const int ftime_hl_h;


extern const int VolumeBar_Show;
extern const RECT volrect;
extern const unsigned int VolumeBar_cColor;
extern const unsigned int VolumeBar_oColor;
extern const unsigned int VolumeBar_bColor;
extern const int VolumeBar_highlight;
/*
extern const int ProgressBar_Show;
extern const RECT pbrect;
extern const unsigned int ProgressBar_cColor;
extern const unsigned int ProgressBar_oColor;
extern const unsigned int ProgressBar_bColor;
extern const int ProgressBar_highlight;
*/





#endif
